### ISSUE TITLE
Document the folder structure

### ISSUE THREAD

**Issue by shntnu** [broadinstitute/cellpainting-gallery#1]
Document the folder structure using these issues/notes as a starting point  

- https://github.com/cytomining/profiling-handbook/issues/54
- https://github.com/jump-cellpainting/aws/issues/53#issue-946391501 
- https://github.com/jump-cellpainting/aws#steps-for-uploading-data-to-s3cellpainting-gallery
- https://github.com/jump-cellpainting/aws/blob/main/DATA_UPLOAD.md

**Comment by ErinWeisbart** [comment]
Does #2 close this issue?

**Comment by shntnu** [comment]
> Does #2 close this issue?

Yes 🎉
