### ISSUE TITLE
Missing cpg datasets in the table (but existing in AWS)

### ISSUE THREAD

**Issue by jasperhyp** [broadinstitute/cellpainting-gallery#104]
**Is your question related to a problem? Please describe.**
Hello, Thanks for creating this gallery. I am looking at datasets in [Quilt](https://open.quiltdata.com/b/cellpainting-gallery/tree/), but it seems there are some cpg datasets there that are not described in the table in README here. Is there a specific reason? Where could we find descriptions of those datasets? E.g. cpg0005, cpg0006, cpg0009, etc. 

**Describe the solution you'd like**
Descriptions added to the README table.

**Describe alternatives you've considered**
Search for metadata/paper. Not found.

**Comment by ErinWeisbart** [comment]
All datasets that are considered complete are listed in our [landing page README](https://github.com/broadinstitute/cellpainting-gallery/blob/main/README.md).

We maintain a [listing of other dataset identifiers](https://broadinstitute.github.io/cellpainting-gallery/prefixes.html), but if a dataset is not listed in our landing page README then it is considered in-progress and, while you are welcome to access it in whatever way you see fit as it is fully public, you may find a variety of data components missing. Eventually, we expect that all in-progress datasets will be completed, but we cannot provide any specific timing or answer any specific questions about any in-progress dataset.

**Comment by jasperhyp** [comment]
Thank you for clarifying!
