### ISSUE TITLE
Readme updates

### ISSUE THREAD

**Issue by bethac07** [broadinstitute/cellpainting-gallery#33]
Jamali et al should be listed as Jamali and Tromans-Coia et al; DOI is https://doi.org/10.1101/2023.02.15.528711

Looks like the second Chandrasekaran will be 2023 so can probably now not do 2022a, etc. 

(Would do these myself but I don't have write access :( )

**Comment by shntnu** [comment]
> (Would do these myself but I don't have write access :( )

Would fork + PR be ok? Trying to see if we can work in that mode for this repo

**Comment by bethac07** [comment]
Shock-gasp, I'm not special? FINE ;)

**Comment by bethac07** [comment]
@shntnu should I wait for #34 so that we don't have to rebase, or would you like me to go ahead and do now?

**Comment by shntnu** [comment]
Please go ahead and do now, and do so via a branch instead of fork if that's easier (you _are_ special as it turns out  😛)

**Comment by bethac07** [comment]
I didn't have to be special! But will do

**Comment by shntnu** [comment]
Addressed in #35
