### ISSUE TITLE
Feature interpretation

### ISSUE THREAD

**Issue by fleurvereijken1999** [broadinstitute/cellpainting-gallery#70]
Hi!

Thank you for the amazing dataset. 
I have difficulty interpreting the features obtained from cell-profiler. I could not find a clear description on all features. Have you done any feature selection and do you know which features are important for predicting compound MoA based on the feature vectors?

**Comment by ErinWeisbart** [comment]
Features are described in more detail in the [Cell Painting wiki](https://github.com/carpenter-singh-lab/2023_Cimini_NatureProtocols/wiki/What-do-Cell-Painting-features-mean%3F).

Yes, feature selection is performed during the process of profile creation. Our whole protocol is described in [Cimini et al "Optimizing the Cell Painting assay for image-based profiling"](https://www.nature.com/articles/s41596-023-00840-9) and it links to the tools we use for profile creation (including feature selection). Those include the [Broad Institute Imaging Platform Profiling Recipe](https://github.com/cytomining/profiling-recipe) and [Broad Institute Imaging Platform Profiling Template](https://github.com/cytomining/profiling-recipe).

We have multiple publications coming soon that will include experiments examining compound MoA prediction in detail but I don't know of anything public to address that question at the moment.
